spring.application.name=shipment
spring.datasource.url=jdbc:postgresql://localhost:5432/shipment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate